title: CafeSG Team Blog

markdown: redcarpet

permalink: /:title/

paginate: 5
paginate_path: "/trang-:num/"

baseurl: ""

#
excerpt_separator: <!--more-->

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME